"""Set up an Autodesk Fusion design for the 4.2" e-Paper desk frame.

GENERATED by tools/mkfusion.py from src/epaper_stand.scad.  Re-run
tools/mkfusion.sh after any parameter change rather than editing this file.

Run it from Fusion: Utilities > ADD-INS > Scripts and Add-Ins > Scripts > the
green + > pick this EinkStandSetup folder > Run.  Scripts are available on the
Personal licence, and nothing here needs a capability Personal restricts.  It
is safe to run twice: a parameter that already exists is updated, and the
keep-out component is rebuilt from scratch.

If it stops, it says which of the two stages it stopped on.  Neither is
load-bearing - fusion/parameters.csv and fusion/keepouts.csv carry the same
numbers, and eight boxes placed by hand from the CSV take about five minutes.

It does two things.

1. Creates the model's INPUT parameters as Fusion user parameters, with the
   comment each one carries in the OpenSCAD source.  These are the measured
   and chosen numbers; everything else in the OpenSCAD model is worked out
   from them, and fusion/reference-dimensions.csv has those answers to check a
   rebuild against.

2. Builds one body per component envelope, named KEEPOUT_<part>, in the
   root component, at the position the layout puts it.  Axes are the model's:
   X = short axis (0 = centre), Y = depth (0 = outer front face), Z = long
   axis (0 = bottom edge).  Those are the same axes the DXF sketches and the
   reference meshes in fusion/ use, so everything lands on one origin.

   The bodies are reference geometry, not parts.  Model the frame and cover
   around them; if plastic and a keep-out ever share space, the plastic is
   wrong.  Two are deliberately generous rather than tight: DRIVER_BOARD is
   the whole 16 mm measured stack - board, sockets and carrier - and
   FPC_HOLLOW is sized for a 180 degree fold that has to have somewhere to go,
   not for the ribbon's own width.
"""

import adsk.core, adsk.fusion, traceback

# name, unit, expression, comment
PARAMETERS = [
    # ---- Panel - measured on the part
    ("pan_w",               "mm",   "76",      "glass and ink, MEASURED on the actual module (Andy, rev E): glass 76 x 90, sharp corners. Dead border 3.0 on three sides, 9.4 on the ribbon side (that is the '10 mm' one, on the 76 axis)."),
    ("pan_h",               "mm",   "90",      "glass and ink, MEASURED on the actual module (Andy, rev E): glass 76 x 90, sharp corners. Dead border 3.0 on three sides, 9.4 on the ribbon side (that is the '10 mm' one, on the 76 axis)."),
    ("pan_t",               "mm",   "1.05",    "glass and ink, MEASURED on the actual module (Andy, rev E): glass 76 x 90, sharp corners. Dead border 3.0 on three sides, 9.4 on the ribbon side (that is the '10 mm' one, on the 76 axis)."),
    ("act_w",               "mm",   "63.6",    "active ink area across the SHORT axis, 400 x 300 px"),
    ("act_h",               "mm",   "84.8",    "active ink area along the LONG axis"),
    ("bez_thin",            "mm",   "3",       "dead border, three sides"),
    # ---- Glass pocket
    ("pan_clr_w",           "mm",   "0.75",    "pocket clearance per side across the WIDTH (76 axis)"),
    ("pan_clr_h",           "mm",   "0.75",    "... and across the LONG axis. Deliberately loose (1.5 mm total): a printed 91.0 measured short, so this is sized for print variance and the glass is taped rather than press-fitted."),
    ("pan_r",               "mm",   "0.5",     "pocket corner radius (relief handles sharp corners)"),
    ("pan_rel",             "mm",   "1.4",     "pocket corner relief, so sharp glass corners seat"),
    # ---- Ribbon route - measured looking at the rear face
    ("rib_exit",            "mm",   "0",       "exit centre, along the long axis, from the glass centre. 0 = dead centre."),
    ("rib_out",             "mm",   "4",       "leg 1, out from the glass edge"),
    ("rib_band",            "mm",   "9",       "ribbon width through the turn"),
    ("rib_run",             "mm",   "20",      "leg 2, toward the TOP"),
    ("rib_leg3",            "mm",   "10",      "leg 3, inboard across the rear face. It only has to LAND on the adapter, not hit a socket - the tail folds over onto it, and the cable on from the adapter to the driver is routed by hand, so nothing ..."),
    ("rib_marg",            "mm",   "10",      "relief margin around the route, along the long axis. OVERSIZE IS FREE HERE - the hollow is only ever a problem when it is too SMALL - so this is set generously rather than to the route. At 10 the ..."),
    ("rib_clr",             "mm",   "3",       "lateral room it needs to bend back around (OUT)"),
    ("rib_dep",             "mm",   "3",       "... and how far BEHIND the glass back face that relief runs, so the 180 deg fold has somewhere to go. Measured off the glass, not off the front face. Without this the relief is only as deep as the ..."),
    ("rib_tail",            "mm",   "18",      "MEASURED: tail length, glass edge to the end of the ribbon, laid flat. The 180 deg fold back on itself at the pocket edge eats about 2*rib_dep of that, so what is left to reach a socket is rib_reach."),
    ("wall_rib",            "mm",   "1",       "minimum wall left outboard of the ribbon notch"),
    # ---- Body
    ("depth",               "mm",   "25",      "outer depth, front face to back face"),
    ("front_t",             "mm",   "1.4",     "front shell thickness, ahead of the glass pocket"),
    ("cover_t",             "mm",   "1.4",     "cover skin thickness"),
    ("wall",                "mm",   "2.2",     "side wall around the PCB cavity"),
    ("corner_r",            "mm",   "5",       "outer corner radius, seen from the front"),
    ("cav_r",               "mm",   "1.5",     "PCB cavity corner radius. Under 1.707 so a sharp corner seats without a relief"),
    ("front_chf",           "mm",   "0.8",     "45 deg edge break on the front face"),
    ("win_chf",             "mm",   "0.9",     "45 deg edge break around the window"),
    ("rear_chf",            "mm",   "2",       "45 deg edge break on the back face. foot_z has to clear it"),
    ("white_show_short",    "mm",   "0.7",     "> win_w = 63.6 + 1.4 = 65.0"),
    ("white_show_long",     "mm",   "1.3",     "> win_h = 84.8 + 2.6 = 87.4"),
    ("reg_step",            "mm",   "1",       "cover register stands this far forward of the skin datum"),
    # ---- Fixings - M2.5 countersunk into heat-set inserts
    ("ins_d",               "mm",   "3.6",     "heat-set insert bore. insert_size = 'M2.5'; MEASURE YOURS"),
    ("ins_l",               "mm",   "4",       "insert length"),
    ("ins_relief",          "mm",   "1",       "extra bore past the insert for displaced plastic"),
    ("scr_free",            "mm",   "2.9",     "screw clearance hole"),
    ("scr_head",            "mm",   "5",       "countersunk head diameter, 90 deg"),
    # ---- Glass retention - tape pads and the cover's glass ribs
    ("tape_len",            "mm",   "40",      "along the SHORT axis (the strip's length)"),
    ("tape_reach",          "mm",   "5",       "along the LONG axis, out from the pocket edge into the 6.25 mm ledge"),
    ("tape_dep",            "mm",   "0.3",     "recessed into the ledge at pcb_face_y"),
    ("rib_gap",             "mm",   "0.25",    "how far the cover's glass ribs stop short of the panel's back face"),
    ("rib_pocket_c",        "mm",   "1",       "material left between the pocket wall and a segment"),
    ("rib_seg",             "mm",   "15",      "segment length, each side"),
    # ---- Electronics - driver board
    ("drv_w",               "mm",   "29.46",   "Waveshare e-Paper ESP32 Driver Board Rev 3. Outline 48.25 x 29.46, off the vendor's mechanical drawing. drv_t is just the bare PCB, used by the rails that grip its edge; drv_env is the whole stack ..."),
    ("drv_h",               "mm",   "48.25",   "Waveshare e-Paper ESP32 Driver Board Rev 3. Outline 48.25 x 29.46, off the vendor's mechanical drawing. drv_t is just the bare PCB, used by the rails that grip its edge; drv_env is the whole stack ..."),
    ("drv_t",               "mm",   "1.6",     "Waveshare e-Paper ESP32 Driver Board Rev 3. Outline 48.25 x 29.46, off the vendor's mechanical drawing. drv_t is just the bare PCB, used by the rails that grip its edge; drv_env is the whole stack ..."),
    ("drv_env",             "mm",   "6",       "total depth, board + tallest part"),
    ("drv_stack",           "mm",   "16",      "MEASURED, and this is the number that decides the depth budget: driver board + female pin sockets + carrier PCB is 16.0 max, back face to tallest point. It is the whole stack in one figure, so it ..."),
    ("fpc_off",             "mm",   "12.5",    "socket centre, from the near end"),
    ("drv_clr",             "mm",   "0.4",     "clearance between the driver board's edge and its rails"),
    # ---- Electronics - driver carrier
    ("carrier_w",           "mm",   "30",      "driver carrier: a 30 x 70 cut of 0.1in double-sided prototype board"),
    ("carrier_h",           "mm",   "70",      "driver carrier, along the long axis. ~14 mm of it is spare board below the driver, for the battery divider"),
    ("carrier_t",           "mm",   "1.6",     "carrier board thickness"),
    ("hdr_h",               "mm",   "8.5",     "female header body: driver's underside to the carrier face"),
    ("carrier_hole",        "mm",   "2",       "hole diameter"),
    ("carrier_hx",          "mm",   "26",      "hole centres, across the short axis"),
    ("carrier_hz",          "mm",   "66",      "hole centres, along the long axis"),
    ("carrier_peg",         "mm",   "0.15",    "peg undersize, so the board drops on rather than presses"),
    ("carrier_pin",         "mm",   "2",       "hole centre to the first header pin - a keep-out, so nothing on the peg may be wider than 2*carrier_pin"),
    # ---- Electronics - FPC adapter
    ("adapt_w",             "mm",   "18",      "Waveshare FPC adapter outline, measured"),
    ("adapt_h",             "mm",   "32",      "Waveshare FPC adapter outline, measured"),
    ("adapt_env",           "mm",   "5",       "board + its two FPC connectors, total depth - CONFIRMED"),
    # ---- Electronics - charger, cell and port
    ("chg_w",               "mm",   "32",      "charger breakout. chg_part = 'bq25185' (Adafruit 6091)"),
    ("chg_h",               "mm",   "26.3",    "charger breakout"),
    ("chg_t",               "mm",   "7.2",     "board + USB-C jack, off the proto face"),
    ("bat_w",               "mm",   "44",      "2000 mAh LiPo, 694449 pouch"),
    ("bat_h",               "mm",   "49",      "2000 mAh LiPo, 694449 pouch"),
    ("bat_t",               "mm",   "6.9",     "2000 mAh LiPo, 694449 pouch"),
    ("bat_clr",             "mm",   "0.8",     "clearance around the cell, per side"),
    ("bat_fence",           "mm",   "1",       "fence rib thickness either side of the cell"),
    ("elec_clr",            "mm",   "1",       "clearance between a board and the cavity wall"),
    ("col_gap",             "mm",   "2",       "gap between the two board columns"),
    # ---- Kickstand
    ("dep_ang",             "deg",  "35",      "swing from folded. The stance knob."),
    ("leg_len",             "mm",   "55",      "pivot to foot tip"),
    ("foot_z",              "mm",   "3",       "where the folded foot tip stops. MUST clear rear_chf (2.0) or the leg hangs over the bottom edge of the frame."),
    ("leg_t",               "mm",   "4",       "thickness at the pivot. Sets piv_y: the pin sits leg_t/2 below the back face so the folded leg is FLUSH."),
    ("leg_tf",              "mm",   "1",       "thickness at the tip. The taper is ONE-SIDED - the back face stays flush and the front face rises - so the thin end fits the shallow recess without standing proud."),
    ("foot_r",              "mm",   "4",       "foot corner radius, in plan"),
    ("heel_z",              "mm",   "4",       "how far the heel reaches past the pin. Longer = more flat to bear on, but it must stay inside rec_top through the sweep."),
    ("pin_d",               "mm",   "2",       "pin, snapped into sockets in the recess side walls"),
    ("pin_fit",             "mm",   "0.1",     "... and its clearance. ALSO the detent's compliance budget: this is how far the leg can lift to let a nub out of the seat."),
    ("rec_dep",             "mm",   "4.5",     "recess depth below the back face"),
    ("rec_shl",             "mm",   "1.4",     "... where solid frame is behind it (below cav_z0), where a deep recess would leave no floor at all"),
    ("rec_w",               "mm",   "18",      "deep recess would leave no floor at all rec_w IS THE PIN LENGTH. The pin spans the pocket exactly: it passes through both ears and its ends finish flush with the pocket's side walls, so the walls ..."),
    ("rec_clr",             "mm",   "0.5",     "clearance between the leg and each EAR"),
    ("rec_wall",            "mm",   "1.5",     "wall left outboard of the pocket in the boss below. Bounded by the driver carrier at x -11.45: the boss reaches +/-10.5, clearing it by 0.95."),
    ("rec_floor",           "mm",   "1.8",     "THE POCKET'S FLOOR, and it has to be built: see recess_boss(). The cover's own register is only cover_t+reg_step thick, and the pocket is rec_dep deep, so the cut goes clean through it. What used to ..."),
    ("det_tot",             "mm",   "0.35",    "how far a nub crest reaches past the heel's flat. Keep it SMALL: the flat is meant to take the load, and a nub that bottoms before the flat lands would lift the flat off."),
    ("det_iw",              "mm",   "0.9",     "seat width along the long axis. Sets how many degrees either end of the stroke the detent is engaged over."),
    ("det_seat",            "mm",   "0.12",    "how much DEEPER the seat is than the track. THE CLICK. PRINT-TUNE: no click, raise it; too stiff to fold, drop it."),
    ("nub_pre",             "mm",   "0.05",    "nub interference against the track, i.e. THE FRICTION that holds the leg wherever it is put. PRINT-TUNE. Won't move, drop it; flops around, raise it 0.02 at a time."),
    ("nub_r",               "mm",   "0.35",    "nub ridge radius. Also sets how far apart the two nubs land, which must stay wider than det_iw or they act as one ridge. Must stay under det_iw/2 or the nub cannot enter the seat."),
    ("nub_root",            "mm",   "0.5",     "how far INSIDE the leg's front face each nub is rooted. A nub whose crest circle clears that face exports as its own loose solid, so this is not cosmetic."),
    ("lip_h",               "mm",   "0.35",    "folded-latch lip overhang. PRINT-TUNE: too much and the leg will not close, none and it will not stay closed."),
    ("lip_z",               "mm",   "5.5",     "... its height, over the leg near the tip"),
    ("lip_w",               "mm",   "1.6",     "... and its width along the long axis"),
    ("ear_w",               "mm",   "2",       "ear thickness, inboard from each pocket wall. With rec_w and rec_clr this sets leg_w: rec_w - 2*(ear_w + rec_clr)."),
    ("ear_mouth",           "",     "0.72",    "socket mouth, as a fraction of the bore. Under 1.0 so the pin snaps past it and is then retained."),
    ("ear_len",             "mm",   "8",       "ear length along the long axis, centred on the pin"),
    # ---- Measured, but not driving geometry in the OpenSCAD model
    ("fpc_w",               "mm",   "16",      "the driver's 24-pin FPC socket body, along the board edge"),
    ("adapt_t",             "mm",   "1.6",     "adapter PCB alone. adapt_env is the figure that decides fit"),
    ("adapt_hole",          "mm",   "2.2",     "ASSUMED M2 clearance. The adapter is taped to the glass, so nothing is bored for it - measure only if that changes"),
    ("adapt_inset",         "mm",   "2",       "ASSUMED hole inset from each edge. Unused while the adapter is taped"),
    ("carrier_pad",         "mm",   "4.5",     "standoff pad diameter under each carrier corner - the pads became locating pegs, so this no longer sets anything"),
    ("usb_w",               "mm",   "13",      "flash-port opening width. flash_port = false, so the port is not cut"),
]

# name, x_min, x_max, y_min, y_max, z_min, z_max, note   (millimetres)
KEEPOUTS = [
    ("PANEL_GLASS",        -41.2,      34.8,     1.55,      2.6,    10.25,   100.25, "bare glass, 76 x 90 sharp corners, measured"),
    ("FPC_HOLLOW",        -44.95,    -41.95,      1.4,     5.45,    40.75,    89.75, "the ribbon's 180 deg fold. Oversized on purpose"),
    ("DRIVER_BOARD",      -41.18,    -11.72,      6.5,     12.5,     15.5,    63.75, "Waveshare e-Paper ESP32 Driver Board Rev 3, full component envelope"),
    ("DRIVER_CARRIER",    -41.45,    -11.45,       21,     22.6,     14.5,     84.5, "0.1in perfboard, 30 x 70, four dia 2.0 holes at 26 x 66 centres"),
    ("FPC_ADAPTER",       -40.45,    -22.45,     2.65,     7.65,    65.75,    97.75, "Waveshare FPC adapter, taped to the back of the glass"),
    ("CHARGER",             6.15,     38.15,     14.9,     22.1,    69.85,    96.15, "Adafruit bq25185 (6091), board + USB-C jack"),
    ("CELL",               -7.65,     36.35,     11.8,     18.7,    18.05,    67.05, "2000 mAh LiPo, 694449 pouch. Squared off - the real pouch has R2 corners"),
    ("USB_C_PIGTAIL",        -12,         2,     13.6,     23.6,    89.75,    94.25, "snap-in rear port, two wires, no data"),
]

KEEPOUT_PREFIX = "KEEPOUT_"          # what groups them, and what a re-run finds
BASE_FEATURE_NAME = "KEEPOUT_bodies"
MM = 0.1   # Fusion's internal length unit is the centimetre


def set_parameters(design):
    params = design.userParameters
    made = updated = 0
    for name, unit, expression, comment in PARAMETERS:
        existing = params.itemByName(name)
        if existing:
            existing.expression = expression
            existing.comment = comment
            updated += 1
        else:
            params.add(name, adsk.core.ValueInput.createByString(expression),
                       unit, comment)
            made += 1
    return made, updated


def snapshot(collection):
    """A plain list, so deleting as we go cannot disturb the iteration."""
    return [collection.item(i) for i in range(collection.count)]


def clear_keepouts(root):
    """Take out whatever a previous run left.

    Deleting the base feature takes its bodies with it; the loop over loose
    bodies afterwards catches a run that was interrupted part way through, and
    the occurrence loop catches designs set up by an earlier version of this
    script, which put the keep-outs in a component of their own.
    """
    for feature in snapshot(root.features.baseFeatures):
        if feature.name.startswith(BASE_FEATURE_NAME):
            feature.deleteMe()
    for body in snapshot(root.bRepBodies):
        if body.name.startswith(KEEPOUT_PREFIX):
            body.deleteMe()
    for occurrence in snapshot(root.occurrences):
        if occurrence.component.name.startswith("KEEPOUT"):
            occurrence.deleteMe()


def build_keepouts(design, root):
    """One body per component envelope, in the ROOT component.

    Not in a component of their own, which is what this script used to do: a
    Part Design document may hold only one component, so addNewComponent fails
    outright there, and these have to work in a part as much as in an assembly.
    The KEEPOUT_ prefix does the grouping instead - it sorts them together in
    the Browser, and it is what clear_keepouts looks for on a re-run.
    """
    clear_keepouts(root)

    temp = adsk.fusion.TemporaryBRepManager.get()
    # A parametric design needs the bodies wrapped in a base feature; a direct
    # modelling design takes them straight.
    direct = design.designType == adsk.fusion.DesignTypes.DirectDesignType
    base = None if direct else root.features.baseFeatures.add()
    if base:
        base.name = BASE_FEATURE_NAME
        base.startEdit()
    try:
        for name, x0, x1, y0, y1, z0, z1, note in KEEPOUTS:
            centre = adsk.core.Point3D.create((x0 + x1) / 2 * MM,
                                              (y0 + y1) / 2 * MM,
                                              (z0 + z1) / 2 * MM)
            obb = adsk.core.OrientedBoundingBox3D.create(
                centre,
                adsk.core.Vector3D.create(1, 0, 0),
                adsk.core.Vector3D.create(0, 1, 0),
                (x1 - x0) * MM, (y1 - y0) * MM, (z1 - z0) * MM)
            solid = temp.createBox(obb)
            if base:
                body = root.bRepBodies.add(solid, base)
            else:
                body = root.bRepBodies.add(solid)
            body.name = KEEPOUT_PREFIX + name
    finally:
        if base:
            base.finishEdit()

    # Opacity after the edit is closed, so it survives it.
    for body in snapshot(root.bRepBodies):
        if body.name.startswith(KEEPOUT_PREFIX):
            try:
                body.opacity = 0.45
            except Exception:
                pass
    return len(KEEPOUTS)


def run(context):
    ui = None
    stage = "starting up"
    try:
        app = adsk.core.Application.get()
        ui = app.userInterface
        design = adsk.fusion.Design.cast(app.activeProduct)
        if not design:
            ui.messageBox("Open a Fusion design first, then run this again.")
            return

        stage = "setting the document to millimetres"
        if design.unitsManager.defaultLengthUnits != "mm":
            design.unitsManager.defaultLengthUnits = "mm"

        stage = "creating the user parameters"
        made, updated = set_parameters(design)

        stage = "building the keep-out bodies"
        bodies = build_keepouts(design, design.rootComponent)

        ui.messageBox(
            "4.2in e-Paper desk frame\n\n"
            "%d parameters created, %d updated\n"
            "%d keep-out bodies, named %s*\n\n"
            "Origin: X = short axis (0 = centre), Y = depth (0 = outer front "
            "face), Z = long axis (0 = bottom edge)."
            % (made, updated, bodies, KEEPOUT_PREFIX))
    except Exception:
        message = ("Stopped while %s.\n\n%s\n"
                   "The same numbers are in fusion/parameters.csv and "
                   "fusion/keepouts.csv, so nothing is lost - the keep-outs "
                   "are eight boxes and the CSV gives their min and max on "
                   "every axis." % (stage, traceback.format_exc()))
        if ui:
            ui.messageBox(message)
        else:
            print(message)
